version: '3.1'

services:

  nginx:
    image: nginx
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - notitas_email

  notitas_email:
    build: ./
    container_name: notitas_email
    tty: true
    ports:
      - 3000:3000
    environment:
      TZ: America/Hermosillo
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    command: sh -c "npm run dev"